# Generated by Django 4.2.11 on 2026-05-25 18:03

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel & Procurement'), ('UTILITY_ELEC', 'Utility Electricity'), ('CORP_TRAVEL', 'Corporate Travel')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(help_text='SHA-256 of the uploaded file; prevents duplicate ingestion', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('row_count_total', models.IntegerField(default=0)),
                ('row_count_success', models.IntegerField(default=0)),
                ('row_count_failed', models.IntegerField(default=0)),
                ('row_count_flagged', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('ingested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier, e.g. "acme-corp"', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField(help_text='Exact parsed row with original field names and values')),
                ('parse_status', models.CharField(choices=[('OK', 'Parsed OK'), ('WARNING', 'Parsed with warnings'), ('ERROR', 'Parse failed')], default='OK', max_length=10)),
                ('parse_errors', models.JSONField(default=list, help_text='List of parse error strings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.ingestionrun')),
            ],
            options={
                'ordering': ['ingestion_run', 'row_number'],
                'unique_together': {('ingestion_run', 'row_number')},
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 – Direct Emissions'), (2, 'Scope 2 – Purchased Energy'), (3, 'Scope 3 – Value Chain')])),
                ('scope_category', models.CharField(help_text='e.g. "1.1 Stationary Combustion", "3.6 Business Travel"', max_length=100)),
                ('activity_type', models.CharField(choices=[('FUEL_STAT', 'Stationary Combustion'), ('FUEL_MOB', 'Mobile Combustion'), ('ELEC', 'Purchased Electricity'), ('FLIGHT', 'Business Travel – Flight'), ('HOTEL', 'Business Travel – Hotel'), ('GROUND', 'Business Travel – Ground Transport'), ('PROCURE', 'Purchased Goods & Services')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit', models.CharField(help_text='Original unit string from source', max_length=20)),
                ('quantity_normalized', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit_normalized', models.CharField(help_text='kWh for electricity, L for liquid fuel, kg for mass, km for distance, nights for hotel', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('site_code', models.CharField(blank=True, db_index=True, help_text='SAP plant code, utility meter ID, or similar site identifier', max_length=50)),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('cost_center', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('currency', models.CharField(blank=True, help_text='ISO 4217', max_length=3)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Source-specific fields preserved verbatim from raw data')),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged for Review'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('review_flags', models.JSONField(default=list, help_text='Auto-detected anomalies: [{code, message, severity}]')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Analyst notes; required when rejecting a record')),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_records', to='ingestion.ingestionrun')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_records', to=settings.AUTH_USER_MODEL)),
                ('raw_record', models.OneToOneField(blank=True, help_text='Source row; null only for manually created records', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='normalized', to='ingestion.rawrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-period_start', 'site_code'],
            },
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_runs', to='ingestion.tenant'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Record Created'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('REJECTED', 'Rejected'), ('NOTE_ADDED', 'Note Added'), ('LOCKED', 'Locked for Audit'), ('UNLOCKED', 'Unlocked')], max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('normalized_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.normalizedrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Null for platform superadmin', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='ingestion.tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='PlantLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(max_length=10)),
                ('plant_name', models.CharField(max_length=255)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('facility_type', models.CharField(choices=[('OFFICE', 'Office'), ('FACTORY', 'Manufacturing Facility'), ('WAREHOUSE', 'Warehouse / Distribution'), ('DATA_CENTER', 'Data Center'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_lookups', to='ingestion.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'plant_code')},
            },
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'review_status'], name='ingestion_n_tenant__3e9974_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'scope', 'period_start'], name='ingestion_n_tenant__b4d91a_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'site_code', 'activity_type', 'period_start'], name='ingestion_n_tenant__525d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'is_locked'], name='ingestion_n_tenant__bde88e_idx'),
        ),
    ]
